#!/bin/bash
NOW=`date +%Y-%m-%d`
java -jar target/Sql4DClient.jar  -bh $(BROKER_HOST) -bp $(BROKER_PORT)  -ch $(COORDINATOR_HOST) -cp $(COORDINATOR_PORT)  -ph $(PROXY_HOST) -pp $(PROXY_PORT) -i $(history_size)
